#!/usr/bin/env python3
# regenerate src/shim/chain_sizes.rs from a pinned Vulkan-Headers checkout (every struct extending VkDeviceCreateInfo)
# usage: gen_chain_sizes.py <Vulkan-Headers dir with include/vulkan and registry/vk.xml>
import os, re, subprocess, sys, tempfile
import xml.etree.ElementTree as ET
if len(sys.argv) != 2:
    sys.exit('usage: gen_chain_sizes.py <Vulkan-Headers dir with include/vulkan and registry/vk.xml>')
hdrs = sys.argv[1]
inc = os.path.join(hdrs, 'include')
core = open(os.path.join(inc, 'vulkan', 'vulkan_core.h')).read()
version = '.'.join(re.search(r'VK_MAKE_API_VERSION\(0, (\d+), (\d+), VK_HEADER_VERSION\)', core).groups()) + '.' + re.search(r'#define VK_HEADER_VERSION (\d+)', core).group(1)
# the macos header set: core, metal and beta (portability subset)
declared = ''.join(open(os.path.join(inc, 'vulkan', f)).read() for f in ('vulkan_core.h', 'vulkan_metal.h', 'vulkan_beta.h'))
rows = []
for t in ET.parse(os.path.join(hdrs, 'registry', 'vk.xml')).getroot().iter('type'):
    if t.get('category') != 'struct' or t.get('alias'):
        continue
    if 'VkDeviceCreateInfo' not in t.get('structextends', '').split(','):
        continue
    name = t.get('name')
    if f'typedef struct {name} {{' not in declared:
        continue
    stype = next(m.get('values') for m in t.findall('member') if m.get('values'))
    rows.append((name, stype))
rows.sort()
src = '#define VK_USE_PLATFORM_METAL_EXT\n#define VK_ENABLE_BETA_EXTENSIONS\n#include <stdio.h>\n#include <vulkan/vulkan.h>\nint main(void) {\n'
src += ''.join(f'    printf("%d %zu\\n", (int){s}, sizeof({n}));\n' for n, s in rows)
src += '    return 0;\n}\n'
with tempfile.TemporaryDirectory() as tmp:
    c = os.path.join(tmp, 'sizes.c')
    open(c, 'w').write(src)
    subprocess.run(['clang', '-arch', 'x86_64', '-m64', '-I', inc, c, '-o', os.path.join(tmp, 'sizes')], check=True)
    out = subprocess.run([os.path.join(tmp, 'sizes')], check=True, capture_output=True, text=True).stdout.split('\n')
sizes = [tuple(int(x) for x in l.split()) for l in out if l]
assert len(sizes) == len(rows)
path = os.path.join(os.path.dirname(__file__), '..', 'src', 'shim', 'chain_sizes.rs')
with open(path, 'w') as f:
    f.write(f'// generated by Scripts/gen_chain_sizes.py from Vulkan-Headers {version} (macos header set); do not edit\n')
    f.write('use ash::vk::StructureType;\n\n')
    f.write(f'pub const SIZES: [(StructureType, usize); {len(rows)}] = [\n')
    for (name, _), (st, size) in zip(rows, sizes):
        f.write(f'    (StructureType::from_raw({st}), {size}), // {name}\n')
    f.write('];\n')
print(f'{len(rows)} entries -> {path}')
